###

# curl --location --request GET 'http://47.98.138.232:80/api/short-link/admin/v1/user/user3'
#--header 'token: 4b312f0b-aa6a-474a-8c20-70b2544c8f97'
#--header 'username: admin'
#--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)'
GET http://47.98.138.232:8000/api/short-link/admin/v1/user/user3
token: 4b312f0b-aa6a-474a-8c20-70b2544c8f97
username: admin
User-Agent: Apifox/1.0.0 (https://apifox.com)

###

ping 159.226.85.247