server:
  port: 8000

management:
  endpoint:
    beans:
      enabled: true

spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev

  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8850