server:
  port: 8000

management:
  endpoint:
    beans:
      enabled: true
secretKey: 123456

spring:
  application:
    name: short-link-gateway
  profiles:
#    active: dev
    active: aggregation
  data:
    redis:
#      host: 47.94.138.232
      host: 47.94.138.232
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.138.232:8848