server:
  port: 8000

logging:
  level:
    com:
      lyl:
        shortlink:
          admin:
            controller: debug
            service: debug
            dao: debug

short-link:
  group:
    max-num: 10

spring:
  application:
    name: short-link-admin
  profiles:
    active: lab

  data:
    redis:
      host: 127.0.0.1
      port: 6379