server:
  port: 8002

logging:
  level:
    com:
      lyl:
        shortlink:
          admin: debug


short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20

management:
  endpoint:
    beans:
      enabled: true

spring:
  application:
    name: short-link-admin
  profiles:
    active: lab

  data:
    redis:
      host: 47.94.138.232
#      host: localhost
      port: 6379