server:
  port: 8001


logging:
  level:
    com:
      lyl:
        shortlink:
          project:
            controller: debug
            service: debug
            dao: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

short-link:
  group:
    max-num: 10
  domain:
    default: nurl.ink:8001
#  amap:
#    key: 2248e268e18ce1393c6ebad7a69a0264
  stats:
    locale:
      amap-key: 2248e268e18ce1393c6ebad7a69a0264
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

spring:
  application:
    name: short-link-project
  profiles:
    active: lab


  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
management:
  endpoint:
    beans:
      enabled: true