server:
  port: 8001


logging:
  level:
    com:
      lyl:
        shortlink:
          project:
            controller: debug
            service: debug
            dao: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

short-link:
  group:
    max-num: 10
  domain:
    default: nurl.ink:8001
  amap:
    key: 2248e268e18ce1393c6ebad7a69a0264

spring:
  application:
    name: short-link-project
  profiles:
    active: home

  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html