server:
  port: 8001


logging:
  level:
    com:
      lyl:
        shortlink:
          project:
            controller: debug
            service: debug
            dao: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

short-link:
  group:
    max-num: 10
  domain:
    default: 127.0.0.1:8000/skip
#  amap:
#    key: 2248e268e18ce1393c6ebad7a69a0264
  stats:
    locale:
      amap-key: 2248e268e18ce1393c6ebad7a69a0264
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com


spring:
  application:
    name: short-link-project
  profiles:
    active: lab


  data:
    redis:
      host: 47.94.138.232
      port: 6379
      password: oRLjnxADacitnfdyEYXtr7

  mvc:
    view:
      prefix: /templates/
      suffix: .html
management:
  endpoint:
    beans:
      enabled: true